### ISSUE TITLE
code for generating fit data

### ISSUE THREAD

**Issue by andrewning** [BYUFLOWLab/VAWTWakeModel#8]
There should be a csv file for the raw cfd data.  It needs to be in a clear format so that others can contribute.  Also need the code used to generate the fit data from the cfd data.

**Comment by ebtingey** [comment]
The code used to generate the fit is now available under 'Cross_Validate_EMG.py' and all of the raw CFD data files can be accessed and downloaded at https://figshare.com/articles/Parameterized_Wake_Model/2059947.  The instructions for integrating the code with the wake model are in /wake_model/data/Figshare.
